CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE booking_statuses (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(20) NOT NULL,
        name character varying(50) NOT NULL,
        description text,
        is_active boolean DEFAULT TRUE,
        display_order integer,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT booking_statuses_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE payment_methods (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(30) NOT NULL,
        name character varying(50) NOT NULL,
        description text,
        is_active boolean DEFAULT TRUE,
        display_order integer,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE payment_statuses (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(20) NOT NULL,
        name character varying(50) NOT NULL,
        description text,
        is_active boolean DEFAULT TRUE,
        display_order integer,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT payment_statuses_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE plans (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        name character varying(100) NOT NULL,
        description text,
        price numeric(10,2) NOT NULL,
        num_classes integer,
        duration_days integer,
        is_active boolean DEFAULT TRUE,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT plans_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE roles (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        name character varying(50) NOT NULL,
        description character varying(255),
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT roles_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE users (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        first_name character varying(100),
        last_name character varying(100),
        email character varying(255) NOT NULL,
        password_hash character varying(255) NOT NULL,
        phone character varying(20),
        is_active boolean DEFAULT TRUE,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        instructor_id uuid,
        CONSTRAINT users_pkey PRIMARY KEY (id),
        CONSTRAINT fk_instructor_user FOREIGN KEY (instructor_id) REFERENCES users (id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE schedules (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        instructor_id uuid NOT NULL,
        start_time timestamp without time zone NOT NULL,
        end_time timestamp without time zone NOT NULL,
        max_students integer,
        is_active boolean DEFAULT TRUE,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT schedules_pkey PRIMARY KEY (id),
        CONSTRAINT fk_instructor_schedule FOREIGN KEY (instructor_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE user_plans (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        user_id uuid NOT NULL,
        plan_id uuid NOT NULL,
        start_date date NOT NULL,
        end_date date NOT NULL,
        remaining_classes integer,
        is_active boolean DEFAULT TRUE,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT user_plans_pkey PRIMARY KEY (id),
        CONSTRAINT fk_plan_user FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE RESTRICT,
        CONSTRAINT fk_user_plan FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE user_roles (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        user_id uuid NOT NULL,
        role_id uuid NOT NULL,
        assigned_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT user_roles_pkey PRIMARY KEY (id),
        CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
        CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE bookings (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        user_id uuid NOT NULL,
        schedule_id uuid NOT NULL,
        user_plan_id uuid NOT NULL,
        status_id integer NOT NULL,
        payment_status_id integer NOT NULL,
        attended_at timestamp without time zone,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT bookings_pkey PRIMARY KEY (id),
        CONSTRAINT fk_booking_payment_status FOREIGN KEY (payment_status_id) REFERENCES payment_statuses (id) ON DELETE RESTRICT,
        CONSTRAINT fk_booking_status FOREIGN KEY (status_id) REFERENCES booking_statuses (id) ON DELETE RESTRICT,
        CONSTRAINT fk_schedule_booking FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_booking FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_plan_booking FOREIGN KEY (user_plan_id) REFERENCES user_plans (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE TABLE payments (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        booking_id uuid NOT NULL,
        amount numeric(10,2) NOT NULL,
        method_id integer NOT NULL,
        status_id integer NOT NULL,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT payments_pkey PRIMARY KEY (id),
        CONSTRAINT fk_booking_payment FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE RESTRICT,
        CONSTRAINT fk_payment_method FOREIGN KEY (method_id) REFERENCES payment_methods (id) ON DELETE RESTRICT,
        CONSTRAINT fk_payment_status FOREIGN KEY (status_id) REFERENCES payment_statuses (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE UNIQUE INDEX booking_statuses_code_key ON booking_statuses (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_bookings_payment_status ON bookings (payment_status_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_bookings_schedule ON bookings (schedule_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_bookings_status ON bookings (status_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_bookings_user ON bookings (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX "IX_bookings_user_plan_id" ON bookings (user_plan_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE UNIQUE INDEX payment_methods_code_key ON payment_methods (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE UNIQUE INDEX payment_statuses_code_key ON payment_statuses (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_payments_booking ON payments (booking_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_payments_method ON payments (method_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_payments_status ON payments (status_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE UNIQUE INDEX roles_name_key ON roles (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_schedules_instructor ON schedules (instructor_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX idx_user_plans_user ON user_plans (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX "IX_user_plans_plan_id" ON user_plans (plan_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX "IX_user_roles_role_id" ON user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE UNIQUE INDEX uk_user_role ON user_roles (user_id, role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE INDEX "IX_users_instructor_id" ON users (instructor_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    CREATE UNIQUE INDEX users_email_key ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201021008_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251201021008_InitialCreate', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251203052857_AddUserStatusColumn') THEN
    ALTER TABLE users DROP COLUMN is_active;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251203052857_AddUserStatusColumn') THEN
    ALTER TABLE users ADD status character varying(1) NOT NULL DEFAULT 'A';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251203052857_AddUserStatusColumn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251203052857_AddUserStatusColumn', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251203200437_AddCertificateTable') THEN
    CREATE TABLE certificates (
        id uuid NOT NULL DEFAULT (uuid_generate_v4()),
        user_id uuid NOT NULL,
        type character varying(50) NOT NULL,
        title character varying(200) NOT NULL,
        description text,
        verification_code character varying(20) NOT NULL,
        pdf_url text,
        blob_file_name character varying(255),
        issued_at timestamp without time zone NOT NULL,
        issued_by_id uuid,
        created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT certificates_pkey PRIMARY KEY (id),
        CONSTRAINT fk_certificate_issued_by FOREIGN KEY (issued_by_id) REFERENCES users (id) ON DELETE SET NULL,
        CONSTRAINT fk_certificate_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251203200437_AddCertificateTable') THEN
    CREATE UNIQUE INDEX certificates_verification_code_key ON certificates (verification_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251203200437_AddCertificateTable') THEN
    CREATE INDEX idx_certificates_user ON certificates (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251203200437_AddCertificateTable') THEN
    CREATE INDEX "IX_certificates_issued_by_id" ON certificates (issued_by_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251203200437_AddCertificateTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251203200437_AddCertificateTable', '9.0.10');
    END IF;
END $EF$;
COMMIT;

